# Generated by Django 5.1.1 on 2024-10-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_invoice_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('service_request', 'Service Request'), ('dealer_payment', 'Dealer Payment'), ('provider_payment', 'Service Provider Payment'), ('service_registration', 'service_registration'), ('Ads', 'Ads'), ('lead_purchase', 'lead_purchase')], max_length=20),
        ),
    ]
