# Generated by Django 5.1.1 on 2024-10-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_invoice_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceregister',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inctive', max_length=10),
        ),
    ]
