# Generated by Django 5.1.1 on 2024-10-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_serviceregister_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='service_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviceregister', to='app1.serviceregister'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicerequests', to='app1.servicerequest'),
        ),
    ]
