# Generated by Django 5.1.1 on 2024-10-26 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_invoice_service_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='service_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviceregister_invoices', to='app1.serviceregister'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicerequests_invoices', to='app1.servicerequest'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='booking_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
